/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package almeribikev1.gui.login;

import java.util.prefs.Preferences;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Gaertan
 */
public class JFrameLogin extends javax.swing.JFrame {
        //obtiene la ruta del archivo java y cambia los . por / para darlos como ruta al path del metodo de prefs para guardar credenciales
     private ControllerLogin controllerLogin;
        String packageName = getClass().getPackage().getName();
        String nodePath = "/" + packageName.replace('.', '/');
    /**
     * Creates new form JFrameLogin
     */
    public JFrameLogin() {
        initComponents();
        controllerLogin = ControllerLogin.getInstance();
        controllerLogin.setJFrameLogin(this);
        controllerLogin.cargarPreferencias();
         jButtonIniciarSesion.addActionListener(controllerLogin);
         jButtonSalir.addActionListener(controllerLogin);
//        cargarPreferencias();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    
//    private void guardarPreferencias(String usuario, String password) {
//
//        
//        Preferences prefs = Preferences.userRoot().node(nodePath);
//        prefs.put("usuario", usuario);
//        prefs.put("password", password);
//    }
//
//    private void borrarPreferencias() {
//
//        
//        Preferences prefs = Preferences.userRoot().node(nodePath);
//        prefs.remove("usuario");
//        prefs.remove("password");
//    }
//    private void cargarPreferencias() {
//    Preferences prefs = Preferences.userRoot().node(nodePath);
//    
//    String usuarioGuardado = prefs.get("usuario", "");
//    String passwordGuardada = prefs.get("password", "");
//    boolean recordar = !usuarioGuardado.isEmpty() && !passwordGuardada.isEmpty();
//    
//    JTFUsuario.setText(usuarioGuardado);
//    JPFLogin.setText(passwordGuardada);
//    jCheckBox1.setSelected(recordar);
//}
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButtonEditMySQL = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        JTFUsuario = new javax.swing.JTextField();
        JPFLogin = new javax.swing.JPasswordField();
        jButtonIniciarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setName("Login"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 103, -1, -1));

        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 223, -1, -1));

        jCheckBox1.setText("Recordar");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 303, -1, -1));

        jButtonEditMySQL.setText("Editar conexion a mySQL");
        jButtonEditMySQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditMySQLActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditMySQL, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        jButtonSalir.setText("Salir");
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, -1));
        getContentPane().add(JTFUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 350, -1));

        JPFLogin.setText("jPasswordField1");
        getContentPane().add(JPFLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 350, -1));

        jButtonIniciarSesion.setText("iniciar sesion");
        getContentPane().add(jButtonIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 120, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButtonEditMySQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditMySQLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditMySQLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameLogin().setVisible(true);
            }
        });
    }

    public String getPackageName() {
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    public String getNodePath() {
        return nodePath;
    }

    public void setNodePath(String nodePath) {
        this.nodePath = nodePath;
    }

    public JPasswordField getJPFLogin() {
        return JPFLogin;
    }

    public void setJPFLogin(JPasswordField JPFLogin) {
        this.JPFLogin = JPFLogin;
    }

    public JButton getjButtonSalir() {
        return jButtonSalir;
    }

    public void setjButtonSalir(JButton jButtonSalir) {
        this.jButtonSalir = jButtonSalir;
    }

    public JCheckBox getjCheckBox1() {
        return jCheckBox1;
    }

    public void setjCheckBox1(JCheckBox jCheckBox1) {
        this.jCheckBox1 = jCheckBox1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField JPFLogin;
    private javax.swing.JTextField JTFUsuario;
    private javax.swing.JButton jButtonEditMySQL;
    private javax.swing.JButton jButtonIniciarSesion;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    public JButton getjButtonIniciarSesion() {
            return jButtonIniciarSesion;    }

    public JTextField getJTFUsuario() {
               return JTFUsuario;    }

    public void setControllerLogin(ControllerLogin aThis) {
        controllerLogin = aThis;}
}


