/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package almeribikev1.gui.login;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Gaertan
 */
public class JFrameConexion extends javax.swing.JFrame {
     private ControllerLogin controllerLogin;
        String packageName = getClass().getPackage().getName();
        String nodePath = "/" + packageName.replace('.', '/');
    /**
     * Creates new form JFrameConexion
     */
    public JFrameConexion() {
        initComponents();
        controllerLogin = ControllerLogin.getInstance();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTFUrl = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        JTFUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JPFPassword = new javax.swing.JPasswordField();
        jButtonReestablecer = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTFUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFUrlActionPerformed(evt);
            }
        });
        getContentPane().add(JTFUrl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 239, -1));

        jCheckBox1.setText("Recordar");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 303, -1, -1));
        getContentPane().add(JTFUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 184, 239, -1));

        jLabel1.setText("Dirección");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 76, -1, -1));

        jLabel2.setText("Usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 156, -1, -1));

        jLabel3.setText("Contraseña");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 233, -1, -1));
        getContentPane().add(JPFPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 240, -1));

        jButtonReestablecer.setText("reestablecer");
        jButtonReestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReestablecerActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReestablecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        jButtonSalir.setText("salir");
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void JTFUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFUrlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFUrlActionPerformed

    private void jButtonReestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReestablecerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReestablecerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameConexion().setVisible(true);
            }
        });
    }

    public ControllerLogin getControllerLogin() {
        return controllerLogin;
    }

    public String getPackageName() {
        return packageName;
    }

    public String getNodePath() {
        return nodePath;
    }

    public JPasswordField getJPFPassword() {
        return JPFPassword;
    }

    public JTextField getJTFUrl() {
        return JTFUrl;
    }

    public JTextField getJTFUsuario() {
        return JTFUsuario;
    }

    public JButton getjButtonReestablecer() {
        return jButtonReestablecer;
    }

    public JButton getjButtonSalir() {
        return jButtonSalir;
    }

    public JCheckBox getjCheckBox1() {
        return jCheckBox1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField JPFPassword;
    private javax.swing.JTextField JTFUrl;
    private javax.swing.JTextField JTFUsuario;
    private javax.swing.JButton jButtonReestablecer;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
